#!/bin/bash
apt-get install python-dev python-mysqldb
apt-get install git
apt-get install python-pip
apt-get install python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose
sudo pip install Django django-admin-tools south
sudo pip install numpy scipy pandas sympy matplotlib ipython ipython-notebook nose scikit-learn --upgrade
sudo pip install cython scikit-image
sudo apt-get install git
sudo apt-get install python-pip
git clone https://github.com/TwistedHardware/roshanRush ~/roshan --depth 1
cd roshan
python manage.py syncdb
python manage.py migrate
python manage.py runserver 0.0.0.0:8080